#!/bin/bash
#| awk 'BEGIN { show=0; } { if ($1 == "Overview") { show = 1;  } else if ( $0 ~ /© 2025 MCP.so/ ) { show = 0 } else if ( show == 1) { print $0 } } ' | less
rm -r chroma_db
echo "loading"
find gh -mindepth 3 -maxdepth 3 -iname README.md | ./insert_chroma.py
